// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v3.20.3
// source: types.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorInfo_ResultCode int32

const (
	ErrorInfo_success ErrorInfo_ResultCode = 0
	ErrorInfo_failed  ErrorInfo_ResultCode = 1
)

// Enum value maps for ErrorInfo_ResultCode.
var (
	ErrorInfo_ResultCode_name = map[int32]string{
		0: "success",
		1: "failed",
	}
	ErrorInfo_ResultCode_value = map[string]int32{
		"success": 0,
		"failed":  1,
	}
)

func (x ErrorInfo_ResultCode) Enum() *ErrorInfo_ResultCode {
	p := new(ErrorInfo_ResultCode)
	*p = x
	return p
}

func (x ErrorInfo_ResultCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorInfo_ResultCode) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[0].Descriptor()
}

func (ErrorInfo_ResultCode) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[0]
}

func (x ErrorInfo_ResultCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorInfo_ResultCode.Descriptor instead.
func (ErrorInfo_ResultCode) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0, 0}
}

type PropItem_PropType int32

const (
	PropItem_none  PropItem_PropType = 0
	PropItem_score PropItem_PropType = 1
)

// Enum value maps for PropItem_PropType.
var (
	PropItem_PropType_name = map[int32]string{
		0: "none",
		1: "score",
	}
	PropItem_PropType_value = map[string]int32{
		"none":  0,
		"score": 1,
	}
)

func (x PropItem_PropType) Enum() *PropItem_PropType {
	p := new(PropItem_PropType)
	*p = x
	return p
}

func (x PropItem_PropType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PropItem_PropType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[1].Descriptor()
}

func (PropItem_PropType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[1]
}

func (x PropItem_PropType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PropItem_PropType.Descriptor instead.
func (PropItem_PropType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1, 0}
}

// 用户类型
type BaseUserInfo_UserType int32

const (
	BaseUserInfo_unknow BaseUserInfo_UserType = 0  //未知
	BaseUserInfo_normal BaseUserInfo_UserType = 1  //正常类型
	BaseUserInfo_robot  BaseUserInfo_UserType = 10 //机器人
)

// Enum value maps for BaseUserInfo_UserType.
var (
	BaseUserInfo_UserType_name = map[int32]string{
		0:  "unknow",
		1:  "normal",
		10: "robot",
	}
	BaseUserInfo_UserType_value = map[string]int32{
		"unknow": 0,
		"normal": 1,
		"robot":  10,
	}
)

func (x BaseUserInfo_UserType) Enum() *BaseUserInfo_UserType {
	p := new(BaseUserInfo_UserType)
	*p = x
	return p
}

func (x BaseUserInfo_UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaseUserInfo_UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[2].Descriptor()
}

func (BaseUserInfo_UserType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[2]
}

func (x BaseUserInfo_UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaseUserInfo_UserType.Descriptor instead.
func (BaseUserInfo_UserType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3, 0}
}

// 用户状态
type BaseUserInfo_UserStatus int32

const (
	BaseUserInfo_none    BaseUserInfo_UserStatus = 0 //没有状态
	BaseUserInfo_free    BaseUserInfo_UserStatus = 1 //站立状态
	BaseUserInfo_sit     BaseUserInfo_UserStatus = 2 //坐下状态
	BaseUserInfo_ready   BaseUserInfo_UserStatus = 3 //同意状态
	BaseUserInfo_lookon  BaseUserInfo_UserStatus = 4 //旁观状态
	BaseUserInfo_playing BaseUserInfo_UserStatus = 5 //游戏状态
	BaseUserInfo_offline BaseUserInfo_UserStatus = 6 //断线状态
)

// Enum value maps for BaseUserInfo_UserStatus.
var (
	BaseUserInfo_UserStatus_name = map[int32]string{
		0: "none",
		1: "free",
		2: "sit",
		3: "ready",
		4: "lookon",
		5: "playing",
		6: "offline",
	}
	BaseUserInfo_UserStatus_value = map[string]int32{
		"none":    0,
		"free":    1,
		"sit":     2,
		"ready":   3,
		"lookon":  4,
		"playing": 5,
		"offline": 6,
	}
)

func (x BaseUserInfo_UserStatus) Enum() *BaseUserInfo_UserStatus {
	p := new(BaseUserInfo_UserStatus)
	*p = x
	return p
}

func (x BaseUserInfo_UserStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BaseUserInfo_UserStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[3].Descriptor()
}

func (BaseUserInfo_UserStatus) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[3]
}

func (x BaseUserInfo_UserStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BaseUserInfo_UserStatus.Descriptor instead.
func (BaseUserInfo_UserStatus) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3, 1}
}

type RoomInfo_RoomType int32

const (
	RoomInfo_none    RoomInfo_RoomType = 0
	RoomInfo_gold    RoomInfo_RoomType = 1  //金币
	RoomInfo_private RoomInfo_RoomType = 16 //私有
	RoomInfo_redPack RoomInfo_RoomType = 32 //红包
)

// Enum value maps for RoomInfo_RoomType.
var (
	RoomInfo_RoomType_name = map[int32]string{
		0:  "none",
		1:  "gold",
		16: "private",
		32: "redPack",
	}
	RoomInfo_RoomType_value = map[string]int32{
		"none":    0,
		"gold":    1,
		"private": 16,
		"redPack": 32,
	}
)

func (x RoomInfo_RoomType) Enum() *RoomInfo_RoomType {
	p := new(RoomInfo_RoomType)
	*p = x
	return p
}

func (x RoomInfo_RoomType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RoomInfo_RoomType) Descriptor() protoreflect.EnumDescriptor {
	return file_types_proto_enumTypes[4].Descriptor()
}

func (RoomInfo_RoomType) Type() protoreflect.EnumType {
	return &file_types_proto_enumTypes[4]
}

func (x RoomInfo_RoomType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RoomInfo_RoomType.Descriptor instead.
func (RoomInfo_RoomType) EnumDescriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4, 0}
}

type ErrorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code ErrorInfo_ResultCode `protobuf:"varint,1,opt,name=code,proto3,enum=bs.types.ErrorInfo_ResultCode" json:"code,omitempty"`
	Info string               `protobuf:"bytes,2,opt,name=info,proto3" json:"info,omitempty"`
}

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	mi := &file_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorInfo) GetCode() ErrorInfo_ResultCode {
	if x != nil {
		return x.Code
	}
	return ErrorInfo_success
}

func (x *ErrorInfo) GetInfo() string {
	if x != nil {
		return x.Info
	}
	return ""
}

type PropItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    PropItem_PropType `protobuf:"varint,1,opt,name=id,proto3,enum=bs.types.PropItem_PropType" json:"id,omitempty"`
	Count int64             `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
}

func (x *PropItem) Reset() {
	*x = PropItem{}
	mi := &file_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PropItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PropItem) ProtoMessage() {}

func (x *PropItem) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PropItem.ProtoReflect.Descriptor instead.
func (*PropItem) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{1}
}

func (x *PropItem) GetId() PropItem_PropType {
	if x != nil {
		return x.Id
	}
	return PropItem_none
}

func (x *PropItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type BaseAppInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type    uint32 `protobuf:"varint,2,opt,name=type,proto3" json:"type,omitempty"`
	Id      uint32 `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Version uint32 `protobuf:"varint,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *BaseAppInfo) Reset() {
	*x = BaseAppInfo{}
	mi := &file_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseAppInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseAppInfo) ProtoMessage() {}

func (x *BaseAppInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseAppInfo.ProtoReflect.Descriptor instead.
func (*BaseAppInfo) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{2}
}

func (x *BaseAppInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BaseAppInfo) GetType() uint32 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *BaseAppInfo) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BaseAppInfo) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type BaseUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Account      string                  `protobuf:"bytes,1,opt,name=account,proto3" json:"account,omitempty"`                                       //用户账号
	UserId       uint64                  `protobuf:"varint,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`                          //用户ID
	GameId       uint64                  `protobuf:"varint,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                          //数字ID
	Gender       uint32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`                                        //性别
	FaceId       uint32                  `protobuf:"varint,5,opt,name=face_id,json=faceId,proto3" json:"face_id,omitempty"`                          //头像id
	CustomFace   string                  `protobuf:"bytes,6,opt,name=custom_face,json=customFace,proto3" json:"custom_face,omitempty"`               //自定义的图像地址
	NickName     string                  `protobuf:"bytes,7,opt,name=nick_name,json=nickName,proto3" json:"nick_name,omitempty"`                     //用户昵称
	Type         BaseUserInfo_UserType   `protobuf:"varint,8,opt,name=type,proto3,enum=bs.types.BaseUserInfo_UserType" json:"type,omitempty"`        //用户类别
	Props        []*PropItem             `protobuf:"bytes,9,rep,name=props,proto3" json:"props,omitempty"`                                           //用户道具
	TableId      uint64                  `protobuf:"varint,10,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`                      //所有桌子
	SeatId       uint32                  `protobuf:"varint,11,opt,name=seat_id,json=seatId,proto3" json:"seat_id,omitempty"`                         //所在位置
	Status       BaseUserInfo_UserStatus `protobuf:"varint,12,opt,name=status,proto3,enum=bs.types.BaseUserInfo_UserStatus" json:"status,omitempty"` //用户状态
	MarketId     uint32                  `protobuf:"varint,13,opt,name=market_id,json=marketId,proto3" json:"market_id,omitempty"`                   //登录主渠道
	SiteId       uint32                  `protobuf:"varint,14,opt,name=site_id,json=siteId,proto3" json:"site_id,omitempty"`                         //登录子渠道
	RegMarketId  uint32                  `protobuf:"varint,15,opt,name=reg_market_id,json=regMarketId,proto3" json:"reg_market_id,omitempty"`        //注册主渠道
	RegSiteId    uint32                  `protobuf:"varint,16,opt,name=reg_site_id,json=regSiteId,proto3" json:"reg_site_id,omitempty"`              //注册子渠道
	RegisterData string                  `protobuf:"bytes,17,opt,name=register_data,json=registerData,proto3" json:"register_data,omitempty"`        //注册时间
	GateConnId   uint64                  `protobuf:"varint,18,opt,name=gate_conn_id,json=gateConnId,proto3" json:"gate_conn_id,omitempty"`           //所在gate
	RoomConnId   uint64                  `protobuf:"varint,19,opt,name=room_conn_id,json=roomConnId,proto3" json:"room_conn_id,omitempty"`           //所在房间
}

func (x *BaseUserInfo) Reset() {
	*x = BaseUserInfo{}
	mi := &file_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseUserInfo) ProtoMessage() {}

func (x *BaseUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseUserInfo.ProtoReflect.Descriptor instead.
func (*BaseUserInfo) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{3}
}

func (x *BaseUserInfo) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *BaseUserInfo) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *BaseUserInfo) GetGameId() uint64 {
	if x != nil {
		return x.GameId
	}
	return 0
}

func (x *BaseUserInfo) GetGender() uint32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *BaseUserInfo) GetFaceId() uint32 {
	if x != nil {
		return x.FaceId
	}
	return 0
}

func (x *BaseUserInfo) GetCustomFace() string {
	if x != nil {
		return x.CustomFace
	}
	return ""
}

func (x *BaseUserInfo) GetNickName() string {
	if x != nil {
		return x.NickName
	}
	return ""
}

func (x *BaseUserInfo) GetType() BaseUserInfo_UserType {
	if x != nil {
		return x.Type
	}
	return BaseUserInfo_unknow
}

func (x *BaseUserInfo) GetProps() []*PropItem {
	if x != nil {
		return x.Props
	}
	return nil
}

func (x *BaseUserInfo) GetTableId() uint64 {
	if x != nil {
		return x.TableId
	}
	return 0
}

func (x *BaseUserInfo) GetSeatId() uint32 {
	if x != nil {
		return x.SeatId
	}
	return 0
}

func (x *BaseUserInfo) GetStatus() BaseUserInfo_UserStatus {
	if x != nil {
		return x.Status
	}
	return BaseUserInfo_none
}

func (x *BaseUserInfo) GetMarketId() uint32 {
	if x != nil {
		return x.MarketId
	}
	return 0
}

func (x *BaseUserInfo) GetSiteId() uint32 {
	if x != nil {
		return x.SiteId
	}
	return 0
}

func (x *BaseUserInfo) GetRegMarketId() uint32 {
	if x != nil {
		return x.RegMarketId
	}
	return 0
}

func (x *BaseUserInfo) GetRegSiteId() uint32 {
	if x != nil {
		return x.RegSiteId
	}
	return 0
}

func (x *BaseUserInfo) GetRegisterData() string {
	if x != nil {
		return x.RegisterData
	}
	return ""
}

func (x *BaseUserInfo) GetGateConnId() uint64 {
	if x != nil {
		return x.GateConnId
	}
	return 0
}

func (x *BaseUserInfo) GetRoomConnId() uint64 {
	if x != nil {
		return x.RoomConnId
	}
	return 0
}

type RoomInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AppInfo   *BaseAppInfo      `protobuf:"bytes,1,opt,name=app_info,json=appInfo,proto3" json:"app_info,omitempty"`
	Kind      uint32            `protobuf:"varint,2,opt,name=kind,proto3" json:"kind,omitempty"`
	Type      RoomInfo_RoomType `protobuf:"varint,3,opt,name=type,proto3,enum=bs.types.RoomInfo_RoomType" json:"type,omitempty"`
	Level     uint32            `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Name      string            `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	BaseScore int64             `protobuf:"varint,6,opt,name=base_score,json=baseScore,proto3" json:"base_score,omitempty"`
	JoinMin   int64             `protobuf:"varint,7,opt,name=join_min,json=joinMin,proto3" json:"join_min,omitempty"`
	JoinMax   int64             `protobuf:"varint,8,opt,name=join_max,json=joinMax,proto3" json:"join_max,omitempty"`
	OutScore  int64             `protobuf:"varint,9,opt,name=out_score,json=outScore,proto3" json:"out_score,omitempty"`
	WinLimit  int64             `protobuf:"varint,10,opt,name=win_limit,json=winLimit,proto3" json:"win_limit,omitempty"`
}

func (x *RoomInfo) Reset() {
	*x = RoomInfo{}
	mi := &file_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomInfo) ProtoMessage() {}

func (x *RoomInfo) ProtoReflect() protoreflect.Message {
	mi := &file_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomInfo.ProtoReflect.Descriptor instead.
func (*RoomInfo) Descriptor() ([]byte, []int) {
	return file_types_proto_rawDescGZIP(), []int{4}
}

func (x *RoomInfo) GetAppInfo() *BaseAppInfo {
	if x != nil {
		return x.AppInfo
	}
	return nil
}

func (x *RoomInfo) GetKind() uint32 {
	if x != nil {
		return x.Kind
	}
	return 0
}

func (x *RoomInfo) GetType() RoomInfo_RoomType {
	if x != nil {
		return x.Type
	}
	return RoomInfo_none
}

func (x *RoomInfo) GetLevel() uint32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *RoomInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RoomInfo) GetBaseScore() int64 {
	if x != nil {
		return x.BaseScore
	}
	return 0
}

func (x *RoomInfo) GetJoinMin() int64 {
	if x != nil {
		return x.JoinMin
	}
	return 0
}

func (x *RoomInfo) GetJoinMax() int64 {
	if x != nil {
		return x.JoinMax
	}
	return 0
}

func (x *RoomInfo) GetOutScore() int64 {
	if x != nil {
		return x.OutScore
	}
	return 0
}

func (x *RoomInfo) GetWinLimit() int64 {
	if x != nil {
		return x.WinLimit
	}
	return 0
}

var File_types_proto protoreflect.FileDescriptor

var file_types_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x62,
	0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x22, 0x7a, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x32, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x1e, 0x2e, 0x62, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f,
	0x64, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x22, 0x25, 0x0a, 0x0a,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x66, 0x61, 0x69, 0x6c, 0x65,
	0x64, 0x10, 0x01, 0x22, 0x6e, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x12,
	0x2b, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x62, 0x73,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x50, 0x72, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x2e,
	0x50, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x22, 0x1f, 0x0a, 0x08, 0x50, 0x72, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08,
	0x0a, 0x04, 0x6e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x10, 0x01, 0x22, 0x5f, 0x0a, 0x0b, 0x42, 0x61, 0x73, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x07, 0x76, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x22, 0x85, 0x06, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x67, 0x61, 0x6d, 0x65,
	0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x67, 0x61, 0x6d, 0x65, 0x49,
	0x64, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x66, 0x61, 0x63,
	0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x66, 0x61, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x5f, 0x66, 0x61, 0x63,
	0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x75, 0x73, 0x74, 0x6f, 0x6d, 0x46,
	0x61, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x33, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1f,
	0x2e, 0x62, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x28, 0x0a, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x18, 0x09,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x62, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e,
	0x50, 0x72, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x52, 0x05, 0x70, 0x72, 0x6f, 0x70, 0x73, 0x12,
	0x19, 0x0a, 0x08, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x07, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65,
	0x61, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x65, 0x61,
	0x74, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0c, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x21, 0x2e, 0x62, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x42,
	0x61, 0x73, 0x65, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72,
	0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x0d, 0x52, 0x08, 0x6d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x73, 0x69,
	0x74, 0x65, 0x49, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x5f, 0x6d, 0x61, 0x72, 0x6b,
	0x65, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0b, 0x72, 0x65, 0x67,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0b, 0x72, 0x65, 0x67, 0x5f,
	0x73, 0x69, 0x74, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x72,
	0x65, 0x67, 0x53, 0x69, 0x74, 0x65, 0x49, 0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x67, 0x69,
	0x73, 0x74, 0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x11, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x20, 0x0a,
	0x0c, 0x67, 0x61, 0x74, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x12, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x0a, 0x67, 0x61, 0x74, 0x65, 0x43, 0x6f, 0x6e, 0x6e, 0x49, 0x64, 0x12,
	0x20, 0x0a, 0x0c, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x63, 0x6f, 0x6e, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x13, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x72, 0x6f, 0x6f, 0x6d, 0x43, 0x6f, 0x6e, 0x6e, 0x49,
	0x64, 0x22, 0x2d, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x75, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x6e, 0x6f, 0x72,
	0x6d, 0x61, 0x6c, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x72, 0x6f, 0x62, 0x6f, 0x74, 0x10, 0x0a,
	0x22, 0x5a, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x08,
	0x0a, 0x04, 0x6e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12, 0x08, 0x0a, 0x04, 0x66, 0x72, 0x65, 0x65,
	0x10, 0x01, 0x12, 0x07, 0x0a, 0x03, 0x73, 0x69, 0x74, 0x10, 0x02, 0x12, 0x09, 0x0a, 0x05, 0x72,
	0x65, 0x61, 0x64, 0x79, 0x10, 0x03, 0x12, 0x0a, 0x0a, 0x06, 0x6c, 0x6f, 0x6f, 0x6b, 0x6f, 0x6e,
	0x10, 0x04, 0x12, 0x0b, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x79, 0x69, 0x6e, 0x67, 0x10, 0x05, 0x12,
	0x0b, 0x0a, 0x07, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x10, 0x06, 0x22, 0xf4, 0x02, 0x0a,
	0x08, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x30, 0x0a, 0x08, 0x61, 0x70, 0x70,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x62, 0x73,
	0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x42, 0x61, 0x73, 0x65, 0x41, 0x70, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x07, 0x61, 0x70, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12,
	0x2f, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e,
	0x62, 0x73, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x52, 0x6f, 0x6f, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61,
	0x73, 0x65, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x62, 0x61, 0x73, 0x65, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f, 0x69,
	0x6e, 0x5f, 0x6d, 0x69, 0x6e, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6a, 0x6f, 0x69,
	0x6e, 0x4d, 0x69, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x6a, 0x6f, 0x69, 0x6e, 0x5f, 0x6d, 0x61, 0x78,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x6a, 0x6f, 0x69, 0x6e, 0x4d, 0x61, 0x78, 0x12,
	0x1b, 0x0a, 0x09, 0x6f, 0x75, 0x74, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x12, 0x1b, 0x0a, 0x09,
	0x77, 0x69, 0x6e, 0x5f, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x08, 0x77, 0x69, 0x6e, 0x4c, 0x69, 0x6d, 0x69, 0x74, 0x22, 0x38, 0x0a, 0x08, 0x52, 0x6f, 0x6f,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x08, 0x0a, 0x04, 0x6e, 0x6f, 0x6e, 0x65, 0x10, 0x00, 0x12,
	0x08, 0x0a, 0x04, 0x67, 0x6f, 0x6c, 0x64, 0x10, 0x01, 0x12, 0x0b, 0x0a, 0x07, 0x70, 0x72, 0x69,
	0x76, 0x61, 0x74, 0x65, 0x10, 0x10, 0x12, 0x0b, 0x0a, 0x07, 0x72, 0x65, 0x64, 0x50, 0x61, 0x63,
	0x6b, 0x10, 0x20, 0x42, 0x11, 0x5a, 0x0f, 0x6d, 0x61, 0x6e, 0x67, 0x6f, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_types_proto_rawDescOnce sync.Once
	file_types_proto_rawDescData = file_types_proto_rawDesc
)

func file_types_proto_rawDescGZIP() []byte {
	file_types_proto_rawDescOnce.Do(func() {
		file_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_types_proto_rawDescData)
	})
	return file_types_proto_rawDescData
}

var file_types_proto_enumTypes = make([]protoimpl.EnumInfo, 5)
var file_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_types_proto_goTypes = []any{
	(ErrorInfo_ResultCode)(0),    // 0: bs.types.ErrorInfo.ResultCode
	(PropItem_PropType)(0),       // 1: bs.types.PropItem.PropType
	(BaseUserInfo_UserType)(0),   // 2: bs.types.BaseUserInfo.UserType
	(BaseUserInfo_UserStatus)(0), // 3: bs.types.BaseUserInfo.UserStatus
	(RoomInfo_RoomType)(0),       // 4: bs.types.RoomInfo.RoomType
	(*ErrorInfo)(nil),            // 5: bs.types.ErrorInfo
	(*PropItem)(nil),             // 6: bs.types.PropItem
	(*BaseAppInfo)(nil),          // 7: bs.types.BaseAppInfo
	(*BaseUserInfo)(nil),         // 8: bs.types.BaseUserInfo
	(*RoomInfo)(nil),             // 9: bs.types.RoomInfo
}
var file_types_proto_depIdxs = []int32{
	0, // 0: bs.types.ErrorInfo.code:type_name -> bs.types.ErrorInfo.ResultCode
	1, // 1: bs.types.PropItem.id:type_name -> bs.types.PropItem.PropType
	2, // 2: bs.types.BaseUserInfo.type:type_name -> bs.types.BaseUserInfo.UserType
	6, // 3: bs.types.BaseUserInfo.props:type_name -> bs.types.PropItem
	3, // 4: bs.types.BaseUserInfo.status:type_name -> bs.types.BaseUserInfo.UserStatus
	7, // 5: bs.types.RoomInfo.app_info:type_name -> bs.types.BaseAppInfo
	4, // 6: bs.types.RoomInfo.type:type_name -> bs.types.RoomInfo.RoomType
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_types_proto_init() }
func file_types_proto_init() {
	if File_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_types_proto_rawDesc,
			NumEnums:      5,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_types_proto_goTypes,
		DependencyIndexes: file_types_proto_depIdxs,
		EnumInfos:         file_types_proto_enumTypes,
		MessageInfos:      file_types_proto_msgTypes,
	}.Build()
	File_types_proto = out.File
	file_types_proto_rawDesc = nil
	file_types_proto_goTypes = nil
	file_types_proto_depIdxs = nil
}
